# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7fe75a86e4adb5d98f237d4ba113803f03e0409e928484a99c900e3134fd1542f7143f761d730a6cf80ecd507dd033aec008bcbe71a4a0e737306418cfb1786

test:
  secret_key_base: 78536ea18efdfd52dbc97c534b939725667f1a7dcae38a83f6735ef3b7362a73d22db2ee582e3a3eab17fbe118412813b397cb7896aad3473643ffe7f11c7d0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
